#! /bin/bash

# проверяем на наличие аргумента
# если нет аргумента запрашиваем его
# аргумент - имя скрипта
[ $1 ] && nameFile=$1 || read -r -p "Enter name script: " nameFile

# если скрипт существует то открываем скрипт для редактирования
# иначе создаем директорию для скрипта, скрипт, и similink

# директория для запуска скриптов $PATH
dir_basic=/home/vitaliy/scripts
# директория для сохранения скриптов
dir_for_script=$dir_basic/scripts_directory

cd $dir_for_script

# директория для скрипта (appointment-назначение)
dir_appointment=$dir_for_script/$nameFile 

# проверка на наличие директории/файла с таким именем 
if [ ! -e $nameFile ];then
    mkdir -p $dir_appointment
    cd $dir_appointment

    # создаем файл с shebang и даем права на запуск
    echo "#! /bin/bash" > $nameFile
    chmod +x $nameFile

    # переходим в базовую директорию и создаем similink на файл
    cd $dir_basic
    ln -s $dir_appointment/$nameFile
    
    # Открываем файл скрипта
    vim $nameFile
else
    # Открываем файл скрипта
    vim $dir_basic/$nameFile
fi

